'use strict';


var EventEmitter = require('events') ,
    util = require('util') ;



function ServerEventEmitter () {
    EventEmitter.call(this) ;
}

util.inherits(ServerEventEmitter, EventEmitter) ;


ServerEventEmitter.prototype.eventTypes = {
	SYSTEM_STATUS        : 'SYSTEM_STATUS',
	SYSTEM_CONFIG_STATUS : 'SYSTEM_CONFIG_STATUS',

	LOGGING_SERVICE_STATUS : 'LOGGING_SERVICE_STATUS',
	LOGGING_CONFIG_STATUS  : 'LOGGING_CONFIG_STATUS',

	GTFS_SERVICE_STATUS            : 'GTFS_SERVICE_STATUS',
	GTFS_SERVICE_CONFIG_STATUS     : 'GTFS_SERVICE_CONFIG_STATUS',
    GTFS_SERVICE_START_DATA_UPDATE : 'GTFS_SERVICE_START_DATA_UPDATE',
	GTFS_DATA_UPDATE_STATUS        : 'GTFS_DATA_UPDATE_STATUS',

	GTFS_REALTIME_SERVICE_STATUS        : 'GTFS_REALTIME_SERVICE_STATUS',
	GTFS_REALTIME_SERVICE_CONFIG_STATUS : 'GTFS_REALTIME_SERVICE_CONFIG_STATUS',

	CONVERTER_SERVICE_STATUS        : 'CONVERTER_SERVICE_STATUS',
	CONVERTER_SERVICE_CONFIG_STATUS : 'CONVERTER_SERVICE_CONFIG_STATUS',
    CONVERTER_SERVICE_STARTED       : 'CONVERTER_SERVICE_STARTED' ,
    CONVERTER_SERVICE_STOPPED       : 'CONVERTER_SERVICE_STOPPED' ,

    DATA_ANOMALY : 'DATA_ANOMALY' ,

    ERROR : 'ERROR',
};


module.exports = new ServerEventEmitter() ;
